apiVersion: apps/v1
kind: Deployment
metadata:
  name: rain-predict
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rain-predict
  template:
    metadata:
      labels:
        app: rain-predict
    spec:
     initContainers:
     - name: init-model
       image: huythai855/rain-prediction  # Dùng một image có sẵn Python để tải mô hình
       command: [
         "sh",
         "-c",
#          "custom_model custom_model --model-url https://huggingface.co/huythaispoj855/rain_prediction  --path ./models"
       ]
       volumeMounts:
       - name: model-volume
         mountPath: /models
      containers:
      - name: rain-predict
        image: huythai855/rain-prediction-predict2
        ports:
        - containerPort: 1509
        livenessProbe:
          httpGet:
            path: /health_check
            port: 1509
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health_check
            port: 1509
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: model-volume
          mountPath: /models
      volumes:
      - name: model-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: rain-predict-service
spec:
  selector:
    app: rain-predict
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1509
  type: LoadBalancer